-- Baseline: esquema tal como estaba antes de adoptar Flyway (generado con
-- pg_dump --schema-only sobre la base local, que tiene el esquema restaurado
-- de producción + la tabla usuario de la Etapa 1 de auth).
--
-- En bases YA existentes (dev local, prod) esta migración no se ejecuta: se
-- usa spring.flyway.baseline-on-migrate=true + baseline-version=1, que marca
-- la base como "ya en la versión 1" sin correr nada. Solo se ejecuta de verdad
-- si alguien levanta una base nueva y vacía desde cero.

CREATE TABLE colaborador (
    id bigint NOT NULL,
    apellido character varying(20) NOT NULL,
    dni character varying(8) NOT NULL,
    email character varying(100),
    fecha_nacimiento date,
    foto_url character varying(255),
    habilitado boolean NOT NULL,
    nombre character varying(15) NOT NULL,
    telefono character varying(15),
    empresa_id bigint,
    puesto_id bigint
);

ALTER TABLE colaborador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME colaborador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE empresa (
    id bigint NOT NULL,
    habilitada boolean NOT NULL,
    nombre character varying(100) NOT NULL,
    ruc character varying(11) NOT NULL
);

ALTER TABLE empresa ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME empresa_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE feriado (
    id bigint NOT NULL,
    descripcion character varying(255),
    fecha date NOT NULL
);

ALTER TABLE feriado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME feriado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE puesto (
    id bigint NOT NULL,
    descripcion character varying(255),
    nombre character varying(50) NOT NULL
);

ALTER TABLE puesto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME puesto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE tienda (
    id bigint NOT NULL,
    direccion character varying(255),
    nombre character varying(40) NOT NULL
);

ALTER TABLE tienda ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tienda_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE turno (
    id bigint NOT NULL,
    es_feriado boolean NOT NULL,
    fecha date,
    hora_entrada time(6) without time zone,
    hora_salida time(6) without time zone,
    colaborador_id bigint NOT NULL,
    empresa_id bigint NOT NULL,
    tienda_id bigint NOT NULL
);

ALTER TABLE turno ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME turno_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE usuario (
    id bigint NOT NULL,
    habilitado boolean NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    username character varying(50) NOT NULL,
    CONSTRAINT usuario_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'COLABORADOR'::character varying])::text[])))
);

ALTER TABLE usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY colaborador ADD CONSTRAINT colaborador_pkey PRIMARY KEY (id);
ALTER TABLE ONLY empresa ADD CONSTRAINT empresa_pkey PRIMARY KEY (id);
ALTER TABLE ONLY feriado ADD CONSTRAINT feriado_pkey PRIMARY KEY (id);
ALTER TABLE ONLY puesto ADD CONSTRAINT puesto_pkey PRIMARY KEY (id);
ALTER TABLE ONLY tienda ADD CONSTRAINT tienda_pkey PRIMARY KEY (id);
ALTER TABLE ONLY turno ADD CONSTRAINT turno_pkey PRIMARY KEY (id);
ALTER TABLE ONLY usuario ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);

ALTER TABLE ONLY puesto ADD CONSTRAINT uk1ag0mwfdwdgbjs02osdc2sij2 UNIQUE (nombre);
ALTER TABLE ONLY empresa ADD CONSTRAINT uk2fqlxbcs4h827hio1qam0dhd3 UNIQUE (nombre);
ALTER TABLE ONLY colaborador ADD CONSTRAINT uk78aqrtg2ah8awl76h22m0iubj UNIQUE (email);
ALTER TABLE ONLY usuario ADD CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username);
ALTER TABLE ONLY feriado ADD CONSTRAINT ukar1tvbci6d2p9vuh69e223atu UNIQUE (fecha);
ALTER TABLE ONLY colaborador ADD CONSTRAINT ukdoervqshey94ia3shfubawy4p UNIQUE (dni);
ALTER TABLE ONLY empresa ADD CONSTRAINT ukfkso2kbttplho71hoeka6px1s UNIQUE (ruc);

CREATE INDEX idx_dni ON colaborador USING btree (dni);
CREATE INDEX idx_email ON colaborador USING btree (email);
CREATE INDEX idx_empresa_id ON colaborador USING btree (empresa_id);

ALTER TABLE ONLY colaborador ADD CONSTRAINT fk4280c1cy6m7y706okib7puela FOREIGN KEY (empresa_id) REFERENCES empresa(id);
ALTER TABLE ONLY colaborador ADD CONSTRAINT fk72j24fpbyi5tvxtiehvivgvh6 FOREIGN KEY (puesto_id) REFERENCES puesto(id);
ALTER TABLE ONLY turno ADD CONSTRAINT fkjhickum7kednn4i4wgmgvkx4u FOREIGN KEY (colaborador_id) REFERENCES colaborador(id);
ALTER TABLE ONLY turno ADD CONSTRAINT fkn24shni2ulr21juf84f8h3yt4 FOREIGN KEY (empresa_id) REFERENCES empresa(id);
ALTER TABLE ONLY turno ADD CONSTRAINT fkqinbqk8roud363u9hkw9hauau FOREIGN KEY (tienda_id) REFERENCES tienda(id);
