-- Plantillas de horario para agilizar la carga de turnos (ver TurnoModalComponent).
-- A propósito sin FK a tienda ni a turno: son solo un atajo de UI para
-- rellenar el formulario, no una relación real con ningún otro dato.
CREATE TABLE turno_predeterminado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hora_entrada TIME(6) NOT NULL,
    hora_salida TIME(6) NOT NULL
);

-- Semilla: las 8 combinaciones más usadas históricamente (turno.hora_entrada
-- / hora_salida agrupado sobre datos reales), cubren ~83% de los turnos
-- cargados en el sistema.
INSERT INTO turno_predeterminado (hora_entrada, hora_salida) VALUES
    ('10:00:00', '20:30:00'),
    ('10:00:00', '21:00:00'),
    ('10:00:00', '14:00:00'),
    ('13:00:00', '20:30:00'),
    ('16:00:00', '20:30:00'),
    ('10:00:00', '19:00:00'),
    ('10:00:00', '22:00:00'),
    ('17:00:00', '20:30:00');
