-- La tabla usuario (Etapa 1 de auth, JWT) nunca llegó a la Supabase de
-- producción real: se creó una sola vez, solo en una BD local, vía
-- Hibernate ddl-auto=update, en el momento en que se escribió el código de
-- Usuario/Role (commit bfd38b6). Poco después V1__baseline.sql se generó
-- con pg_dump sobre esa misma BD local — por eso el baseline "cree" que
-- toda base ya tiene usuario, pero ninguna base restaurada desde un dump
-- real de prod (incluida la actual, y cualquier futura en Neon) la trae.
-- Con spring.flyway.baseline-on-migrate=true, esas bases se marcan como
-- "ya en V1" sin volver a correrlo, así que sin esta migración quedan sin
-- la tabla para siempre. Prod (Supabase) queda tal como está — decisión
-- del 14 ago 2026 de trabajar desde acá en adelante sobre la BD local y
-- migrarla a Neon cuando esté lista, en vez de tocar la Supabase vieja.
--
-- IF NOT EXISTS: no rompe una base nueva desde cero, donde V1 ya la creó.
CREATE TABLE IF NOT EXISTS usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    habilitado BOOLEAN NOT NULL,
    CONSTRAINT usuario_role_check CHECK (role IN ('ADMIN', 'COLABORADOR')),
    CONSTRAINT uk_usuario_username UNIQUE (username)
);
