spring.application.name=shift-manager

# Configuración de H2
spring.datasource.url=jdbc:h2:mem:sportcenterdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.pathmatch.matching-strategy=ant-path-matcher
