spring.application.name=shift-manager

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shiftmanager
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

cloudinary.cloud-name=dqelrk3cb
cloudinary.api-key=573872982986831
cloudinary.api-secret=N_jvHL1QRTFFFud6fFvKxtR6euo
